name: flutter_yandex_appmetric
description: Flutter plugin for Yandex AppMetric
version: 0.0.1+3
author: Ivan Saprykin <kartoshka95@gmail.com>
homepage: https://github.com/Ivansap/flutter_yandex_appmetric

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.example.flutter_yandex_appmetric
    pluginClass: FlutterYandexAppmetricPlugin

